"""
S5 / step 07 - the cleaning report and the cumulative token count.

The assignment's second half: "the cleaning continues toward the cumulative
target, now aimed at the slots the mixture shows to be starved." This turns the
pipeline's stats into that accounting - what S4 delivered, what S5 added, which
starved lane each addition was aimed at, and how much of it qualifies for the
anneal reserve.

Run: python scripts/07_cleaning_report.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATS = json.loads((ROOT / "stats" / "s5_pipeline_stats.json").read_text(encoding="utf-8"))
MANIFEST = json.loads((ROOT / "manifests" / "s5_shard_manifest.json").read_text(encoding="utf-8"))
PROV = [json.loads(l) for l in (ROOT / "data" / "raw" / "provenance.jsonl").read_text(
    encoding="utf-8").splitlines() if l.strip()]
MIX = json.loads((ROOT / "mixture" / "v5_mixture.json").read_text(encoding="utf-8"))
OUT = ROOT / "results" / "cleaning_report.md"

S4_TOKENS = 63_080_000        # measured in Session 4 (sarvamai/samvaad-hi-v1, 11 shards)
S4_RAW = 63_350_000

STARVED = {
    "agentic": "supply 0.63B - must be synthesised",
    "reasoning": "supply 85B - needs repetition",
    "long_context": "supply 100B - needs repetition",
    "indic": "supply 276B - needs repetition; the *verified* tier is the real constraint",
}


def n(x):
    return f"{x:,}"


def main():
    st = STATS["stages"]
    lanes = st["8_band_and_manifest"]["lanes"]
    total = st["8_band_and_manifest"]["total_tokens"]
    reserve = st["8_band_and_manifest"]["reserve_tokens"]
    fert = st["8_band_and_manifest"].get("fertility_tokens_per_word", {})

    L = ["# S5 cleaning pass - aimed at the starved lanes\n"]
    L.append(f"_Generated by `scripts/07_cleaning_report.py` from `stats/s5_pipeline_stats.json` "
             f"and `manifests/s5_shard_manifest.json`. Wall time "
             f"{STATS.get('wall_seconds', 0)/60:.1f} min._\n")

    L.append("## Cumulative token target\n")
    L.append("| session | corpus | raw tokens | clean tokens | aimed at |")
    L.append("|---|---|---:|---:|---|")
    L.append(f"| S4 | `sarvamai/samvaad-hi-v1` | {n(S4_RAW)} | {n(S4_TOKENS)} | "
             f"Indic conversational (Hindi/Hinglish) |")
    L.append(f"| S5 | 7 lanes, 30 sources | - | {n(total)} | the four starved lanes below |")
    L.append(f"| **cumulative** | | | **{n(S4_TOKENS + total)}** | |")
    L.append("")

    L.append("## What each addition was aimed at\n")
    L.append("| lane | mixture verdict | docs cleaned | clean tokens | supervised tokens | "
             "supervised share |")
    L.append("|---|---|---:|---:|---:|---:|")
    for lane, v in sorted(lanes.items(), key=lambda kv: -kv[1]["tokens"]):
        verdict = STARVED.get(lane, "covered by real supply")
        sup_pct = 100 * v["sup_tokens"] / max(1, v["tokens"])
        L.append(f"| **{lane}** | {verdict} | {n(v['docs'])} | {n(v['tokens'])} | "
                 f"{n(v['sup_tokens'])} | {sup_pct:.1f}% |")
    L.append("")
    ag = lanes.get("agentic")
    if ag:
        L.append(f"> The agentic lane is **{100*ag['sup_tokens']/max(1,ag['tokens']):.1f}% "
                 f"supervised by token**: of {n(ag['tokens'])} tokens only "
                 f"{n(ag['sup_tokens'])} carry loss. The rest are tool schemas, user "
                 f"turns and observation slots that the model reads but must never be "
                 f"trained to reproduce. A lane sized on raw dataset bytes would have "
                 f"over-counted this lane by "
                 f"{ag['tokens']/max(1,ag['sup_tokens']):.1f}x.\n")

    L.append("## Anneal reserve: how much actually qualifies\n")
    L.append("The admission criteria in `mixture/v5_mixture.json` applied to real documents.\n")
    L.append("| lane | clean tokens | reserve-admitted tokens | fill rate |")
    L.append("|---|---:|---:|---:|")
    for lane, v in sorted(lanes.items()):
        L.append(f"| {lane} | {n(v['tokens'])} | {n(v['reserve_tokens'])} | "
                 f"{100*v['reserve_tokens']/max(1,v['tokens']):.1f}% |")
    L.append(f"| **total** | **{n(total)}** | **{n(reserve)}** | "
             f"**{100*reserve/max(1,total):.1f}%** |")
    L.append("")
    amix = MIX["anneal_reserve"]["mixture_pct"]
    atot = MIX["anneal_reserve"]["tokens"]
    L.append("What those fill rates imply for the declared reserve, lane by lane:\n")
    L.append("| lane | reserve demand | measured fill rate | cleaned pool needed to fill it |")
    L.append("|---|---:|---:|---|")
    for lane, v in sorted(lanes.items()):
        demand = atot * amix.get(lane, 0) / 100.0
        fr = v["reserve_tokens"] / max(1, v["tokens"])
        need = f"{demand/fr/1e12:.2f}T" if fr > 0 else "**unreachable at this fill rate**"
        L.append(f"| {lane} | {demand/1e9:.0f}B | {100*fr:.1f}% | {need} |")
    L.append("")
    L.append("> This is the whole argument for the reserve in one table. The lanes fed by "
             "curated sources fill easily - a public-domain book *is* long-context "
             "reserve material, so that fill rate is high by construction. The two lanes "
             "the model is actually being built for do not fill: at the measured 0.6% "
             "agentic fill rate, a 10B agentic reserve would need ~1.7T of cleaned "
             "agentic-lane candidates, and no such pool exists (total real supply is "
             "0.63B). At the measured 0% reasoning fill rate it cannot be filled at all "
             "from open data. Both have to be manufactured deliberately, which is exactly "
             "why the reserve is a Session-5 allocation decision and not something "
             "discovered at the end of the run.\n")

    L.append("## Pipeline stages (real counts)\n")
    L.append("| stage | in | out | note |")
    L.append("|---|---:|---:|---|")
    order = ["1_extract", "2_normalize", "3_language_id", "4_quality_filter", "5_dedup",
             "6_pii_scrub", "7_decontaminate", "8_band_and_manifest"]
    for k in order:
        v = st.get(k, {})
        din = v.get("docs_in", v.get("docs", ""))
        dout = v.get("docs_out", v.get("docs", ""))
        extra = {kk: vv for kk, vv in v.items()
                 if kk not in ("docs", "docs_in", "docs_out", "lanes", "per_lang",
                               "rejected", "note", "fertility_tokens_per_word")
                 and not isinstance(vv, dict)}
        if k == "6_pii_scrub":
            extra = {"redactions": v.get("redactions")}
            din = dout = st["5_dedup"]["docs_out"]
        if k == "7_decontaminate":
            dout = din - v.get("benchmark_overlap_removed", 0) - v.get("industry_canary_hits", 0)
        note = ", ".join(f"{kk}={vv}" for kk, vv in extra.items())[:170]
        L.append(f"| {k} | {n(din) if isinstance(din,int) else din} | "
                 f"{n(dout) if isinstance(dout,int) else dout} | {note} |")
    L.append("")
    qf = st["4_quality_filter"]
    L.append(f"Quality-filter rejections: `{qf.get('rejected')}`\n")
    dd = st["5_dedup"]
    L.append(f"Dedup: {dd['exact_removed']:,} exact + {dd['near_removed']:,} near duplicates "
             f"removed ({dd['method']}).\n")
    dc = st["7_decontaminate"]
    L.append(f"Decontamination: {dc['benchmark_overlap_removed']:,} documents removed for "
             f"10-word-shingle overlap against a {dc['heldout_probes']:,}-problem GSM8K test "
             f"hold-out; {dc['industry_canary_hits']} BIG-bench canary hits.\n")

    if fert:
        L.append("## Fertility of the S5 tokenizer (tokens per whitespace word)\n")
        L.append("_A 32k byte-level BPE trained here on a lane-balanced sample - not the "
                 "200k production vocab from Session 3, so these are upper bounds. Reported "
                 "because the Indic lane's real cost in the budget is tokens, not words._\n")
        L.append("| language | fertility |")
        L.append("|---|---:|")
        for k, v in sorted(fert.items(), key=lambda kv: kv[1]):
            L.append(f"| {k} | {v:.2f} |")
        L.append("")

    L.append("## Per-lane band distribution\n")
    L.append("| lane | D0 | D1 | D2 | D3 | D4 | L0 | L1 | L2 | L3 | L4 |")
    L.append("|---|" + "---:|" * 10)
    for lane, v in sorted(lanes.items()):
        d = v["difficulty"]
        b = v["length_band"]
        row = [str(d.get(x, 0)) for x in ("D0", "D1", "D2", "D3", "D4")] + \
              [str(b.get(x, 0)) for x in ("L0_direct", "L1_short", "L2_medium",
                                          "L3_long", "L4_ultra")]
        L.append(f"| {lane} | " + " | ".join(row) + " |")
    L.append("")

    L.append("## Provenance\n")
    L.append(f"{len(PROV)} source files, every one recorded in `data/raw/provenance.jsonl` "
             f"with url, licence, sha256, byte count and fetch timestamp.\n")
    L.append("| lane | source | licence | MB | docs |")
    L.append("|---|---|---|---:|---:|")
    for p in PROV:
        L.append(f"| {p['lane']} | `{p['source']}` | {p['license']} | "
                 f"{p['bytes']/1e6:.2f} | {p['docs']:,} |")
    L.append("")
    L.append("## Shards\n")
    L.append("| shard | lane | reserve | docs | tokens | sha256 (first 16) |")
    L.append("|---|---|---|---:|---:|---|")
    for m in MANIFEST:
        L.append(f"| `{m['shard']}` | {m['lane']} | {m['reserve']} | {n(m['docs'])} | "
                 f"{n(m['tokens'])} | `{m['content_sha256'][:16]}` |")
    L.append("")

    OUT.write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L[:60]))
    print(f"\n-> {OUT}")


if __name__ == "__main__":
    main()
